### ISSUE TITLE
Bug with sublime text 3113 and 3114

### ISSUE THREAD

**Issue by excetara2** [aziz/SublimeFileBrowser#120]
I have reverted back to 3107 because both theses versions when changing folders it either updates slowly or it leave the older folder remnants from the previous folder there until you move in the buffer and then everything is updated correctly.

Also can you change the width between the icons showing the git status (and folds) and the file names? Is it possible to move them closer together?

**Comment by vovkkk** [comment]
I do not confirm regression neither in 3113 nor in 3114, and upgrades were seamless for me.

Try to remove cache file:
1. `Preferences` → `Browse Packages…`
2. Exit ST.
3. Go up from folder was open in (1), and then to `Cache/FileBrowser`.

If it won’t help, try [older versions](https://github.com/aziz/SublimeFileBrowser/releases) especially 0.7.13 which uses “good” ol’ tmLanguage instead of sublime-syntax, you can either revert using git, or download a zip file; make sure then that `Installed Packages` folder does not contain `FileBrowser.sublime-package` or you can open this file as zip and modify it according to certain version.
I know tedious, but oh well. 



> Also can you change the width between the icons showing the git status (and folds) and the file names? Is it possible to move them closer together?

There is just one whitespace, so no, I think not.

**Comment by excetara2** [comment]
Is it possible to change it to have no whitespace inbetween?

Okay I will try again this weekend removing the cache after upgrading and see if that helps.

**Comment by vovkkk** [comment]
> Is it possible to change it to have no whitespace inbetween?

As an option? yes, but it would need to make many wee changes (syntax, get icon methods, etc.) I’m not willing to do, frankly.

**Comment by excetara2** [comment]
Yes that is fair but can you point me to the code where the space is put in so I can change it to not have a space just in my fork.

**Comment by vovkkk** [comment]
I’m not sure if it is full list:
Syntax files (tmLanguage and sublime-syntax), common.py (`_get_name_point`, `prepare_filelist`), dired.py (`traverse_tree`).

**Comment by excetara2** [comment]
Yeah I see it requires many changes. I could get it to display no problem by changing those functions but then nothing was selectable. I changed the language file to what I thought was correct but  it didn't seem to work. Where are the syntax files stored as I may have a look later at this to see if I can get it working.

**Comment by vovkkk** [comment]
Syntax files are stored in the same location as other files of the plugin.

Normally they are packed in sublime-package file in `Installed Packages`, and then one could create folder with the same name as sublime-package in `Packages` so non-python files placed in this folder will be used instead of those in sublime-package.

Or if there are no sublime-package file, then everything in a subfolder of `Packages`.

However, when you change something in plugin, then often than always you have to properly reload plugin: I usually prefer to restart ST for it, but adding plugin name into ignored_packages in global settings files, save it, remove plugin name, save it — might be enough to reload it sometimes.

**Comment by excetara2** [comment]
I have checked the older versions out with git but still has the same issue so I am not sure what is going on. This is an example of what happens below but it seems to fix itself like a one or two seconds later automatically and remove the old results from the previous folder. It only happens when jumping too but with normal navigation everything works fine.

![image](https://cloud.githubusercontent.com/assets/741078/15804529/4ba1e296-2b4f-11e6-81c5-af6a4fd3441b.png)

**Comment by excetara2** [comment]
So I have dug a little further because was going to try to force a refresh and I noticed it is getting caught in the show command somewhere because it doesn't display the note finished jumping to point until 1 or 2 seconds after the jump so I think this is the issue but can't seem to figure out where or why it is getting caught now and didn't happen before.

**Comment by vovkkk** [comment]
Do you mean show function (defined in show.py)? because there is no show command, iirc; commands are classes in Python.

If you say that problem happen when call show function, and normal navigation works fine;
then I’m thinking that some other plugin interferes, because difference between show and normal navigation is that show in some cases creates new view, so the event `on_load` triggers corresponding method of some EventListener; I guess.

Try on clean [profile](http://www.sublimetext.com/docs/3/revert.html), don’t forget back up precious stuff.

**Comment by excetara2** [comment]
Yes the show function in show.py but I've realized it happens with other things involving the quick panel as well. Something must have changed with the way the quick panel calls actions to be completed in the newest versions. It also happens with other apps that paste/update from the quick panel at least on my machine.

**Comment by excetara2** [comment]
Yes it's a problem with osx and the current version as other users have had this problem so nothing to do with the plugin. Sorry to waste your time.

**Comment by vovkkk** [comment]
> other users have had this problem

Is there some forum thread or something? just for the reference

**Comment by excetara2** [comment]
Yes I found it at the top of the sublime forum with macosx users and
changing tabs but that linked to another post a couple days earlier woth a
solution. Need to change a setting for the gpu in user preferences and all
works good. I'm not at computer so will have to find the link again later.

**Comment by excetara2** [comment]
Here is the link:

https://forum.sublimetext.com/t/tab-switching-display-render-error-in-3114-bug/20605/2
