### ISSUE TITLE
Can't change color scheme

### ISSUE THREAD

**Issue by eduarddotgg** [aziz/SublimeFileBrowser#45]
i have added
{
  "color_scheme": "Packages/User/dired.hidden-tmTheme"
}

to user sittings of file browser, but it doesnt work botho on mac ox 10.10 and windows 8.

could you please help me?
thank you!

**Comment by wilkerfoureaux** [comment]
google brought me here, and I found the following solution for my problem, using material theme:

-- in the console run this: 'view.settings().erase("color_scheme")'

Perhaps because i'm using my Sublime in dropbox folder, causes this bug.

thanks for FichteFoll in https://forum.sublimetext.com/t/cant-change-color-scheme-on-current-project-workspace/15500/2
