### ISSUE TITLE
Make full paths searchable in quick panels for project anf jump points

### ISSUE THREAD

**Issue by Blum** [aziz/SublimeFileBrowser#78]
Hello,
thanks for the great plugin.

Is there any way I can get Project specific Jump points? I mean the jump point to be different for each project of mine.

And also, when I go to the filebrowser and raise the jump point list, I can search in it by typing part of the jump point name. I think it would be very useful if I could search by the path of the jump point (relative to the project) as well.

Cheers

**Comment by vovkkk** [comment]
About jump points see #76 

About search, this is intresting because when you use Goto Anything it does search both lines for each item (and the second line is full path), but when you got custom quick panel it searches only first line of each item, and I don’t see any flag or something to change it, so we have to include full path into first string to make it searchable, I’ll experement with it this weekend probably.

**Comment by vovkkk** [comment]
I think we should abandon second row at all, because full path would be seachable only if it is presented in first row and if we include it there and keep second one it looks messy:

![2015-03-28 04-26-25](https://cloud.githubusercontent.com/assets/1975298/6878109/9e879f40-d502-11e4-818d-8221a5a904ae.png)

And with single row it looks like this:

* project  
    ![2015-03-28 04-20-26](https://cloud.githubusercontent.com/assets/1975298/6878125/cc56674e-d502-11e4-8f34-ba17b73c534e.png)
* points  
    ![2015-03-28 04-21-29](https://cloud.githubusercontent.com/assets/1975298/6878127/d61a4886-d502-11e4-9cc1-fb19dc440aa7.png)

What y’all think?

P.S. Monospace font need to keep it aligned, despite I would prefer normal one, but using tab chars with normal font doesn’t work as I expected, so monospace is only option it seems.

**Comment by Blum** [comment]
Yes, second row looks cool, but since it is not searchable.. In one row looks good too. I like it. 

About "Goto Anything" yes, it is ultimately cool, but what I dislike about it is that it searches for files only. I want to search for a folder and list it. That's why I'm using fileBrowser.

Thanks
