### ISSUE TITLE
Proposal: Faster moving around the file tree

### ISSUE THREAD

**Issue by andradei** [aziz/SublimeFileBrowser#79]
This plugin is awesome! What would make it even awesomer is the ability to have commands like:

`<count> j, k` or `<count> down, up` to move faster through the file tree.

Eg: `10 + j` would go 10 nodes down instead of hitting `j` ten times.

**Comment by vovkkk** [comment]
Well, if I understand you right, you mean arbitrary sequences like `10j` or `11j` or `9000j` etc.
I’ve no idea how to do it; dealing with another issue you reported I looked at Vintageous’ code since it handles arbitrary sequences, and, man, complexity is too damn high, tbh.

So can only suggest to try [LineJumper](https://packagecontrol.io/packages/LineJumper) which supports only certain amount of lines, not what you ask, but at least something.

**Comment by andradei** [comment]
I appreciate the honesty and short response time.

I might even try to submit a PR if I have time.
