### ISSUE TITLE
Conflict with Vintageous

### ISSUE THREAD

**Issue by zhuzelong** [aziz/SublimeFileBrowser#81]
OS: Mac OS X 10.10.3

When open a new blank window in ST3, everything in FileBrowser works fine.

Quit ST3 then directly open a text file (e.g. .tex, .py), and invoke the File Browser by pressing F1, then most of the key ("o", "enter", "H" etc.) fails. 

I suspect the cause is Vintageous because it did not happen in the ST3 builtin "Vintage" mode but went wrong after I enable "Vintageous".

**Comment by vovkkk** [comment]
Did you add disable setting? https://github.com/guillermooo/Vintageous/issues/820#issuecomment-89406502

**Comment by aziz** [comment]
@vovkkk  why don't we add  `"__vi_external_disable": true` to FileBrowser's default settings file to solve this problem for everyone?

**Comment by vovkkk** [comment]
Well, I didn’t do so because 1) not everyone need this, 2) Vintageous’ author wasn’t sure if it even works so it’s kinda “unofficial” setting.
On second thought, ofc, one more setting wouldn’t hurt those who don’t use Vintageous and since it works for now for those who use then it’s alright, I guess.
I’ll do it right now and bump version.
