### ISSUE TITLE
Shortcut to toggle to the sidebar

### ISSUE THREAD

**Issue by thetutlage** [aziz/SublimeFileBrowser#88]
In Sublime i can use `Ctrl+0` to shift focus from and to sidebar, what about doing same ?

**Comment by aziz** [comment]
Since it's a normal view you can use normal sublime commands to toggle between groups.
For example I've this `[super+k, super+k]` that runs `focus_neighboring_group` command which does the job most of the time. 
If you've got a more complex layout maybe using a more specific command like `focus_group` with args `{"group": 0}` would be more helpful.
